version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      # 09:00 every day
      cronjob: "0 9 * * *"
    groups:
      # Use single PR
      dependencies:
        patterns:
          - "*"
