version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      # 09:00 every day
      cronjob: "0 9 * * *"
    groups:
      # Use single PR
      uv:
        patterns:
          - "*"
    allow:
      # Direct and indirect dependencies
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      # 09:00 every day
      cronjob: "0 9 * * *"
    groups:
      # Use single PR
      github-actions:
        patterns:
          - "*"
    allow:
      # Direct and indirect dependencies
      - dependency-type: "all"
