name: Bump version

on:
  workflow_dispatch:
    inputs:
      update_type:
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
        new_version: ${{ steps.new_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Bump version locally
        run: "uv version --no-sync --bump ${{ inputs.update_type }}"

      - name: Get new version
        id: new_version
        run: echo "value=$(uv version --short)" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: dtekcth/workflows/.github/actions/create-release@f083b5a9bb13c9f38ef0fb464d54730da077af47 # main
        with:
          new_version: ${{ steps.new_version.outputs.value }}

  build-and-push-image:
    uses: dtekcth/workflows/.github/workflows/docker-publish.yml@f045e0ae7cc9a754845c5738049965d7bd3b9126 # v1.2.0
    needs: bump-version
    permissions:
      contents: read
      packages: write
